apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-app
  namespace: PLACEHOLDER_NAMESPACE
  labels:
    app: schedule-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule-app
  template:
    metadata:
      labels:
        app: schedule-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values: schedule-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: schedule-app
        image: PLACEHOLDER_CONTAINER_REGISTRY/PLACEHOLDER_IMAGE_REPOSITORY:PLACEHOLDER_TAG
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "100m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet: 
            path: /health/ready
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8081"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ProducerSettings__Host
          value: rabbitmq-service
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: db-connection
              key: ConnectionStrings__DefaultConnection
        - name: ConnectionStrings__DatabaseDllConnection
          valueFrom:
            secretKeyRef:
              name: db-connection
              key: ConnectionStrings__DatabaseDllConnection
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-app-service
  namespace: PLACEHOLDER_NAMESPACE
spec:
  selector:
    app: schedule-app
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8081
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: schedule-app-hpa
  namespace: PLACEHOLDER_NAMESPACE
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: schedule-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30