apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-app
  namespace: PLACEHOLDER_NAMESPACE
  labels:
    app: schedule-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule-app
  template:
    metadata:
      labels:
        app: schedule-app
    spec:
      containers:
      - name: schedule-app
        image: PLACEHOLDER_CONTAINER_REGISTRY/PLACEHOLDER_IMAGE_REPOSITORY:PLACEHOLDER_TAG
        ports:
        - containerPort: 8081
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8081"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: db-connection
              key: ConnectionStrings__DefaultConnection
        - name: ConnectionStrings__DatabaseDllConnection
          valueFrom:
            secretKeyRef:
              name: db-connection
              key: ConnectionStrings__DatabaseDllConnection
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-app-service
  namespace: PLACEHOLDER_NAMESPACE
spec:
  selector:
    app: schedule-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8081
  type: ClusterIP