trigger:
  branches:
    include:
      - feat/pipelines
  paths:
    exclude:
      - README.md

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Preflight
  displayName: Build and Test API
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Show ws files.
          echo $(ls)
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '$(System.DefaultWorkingDirectory)\src\Fiap.Health.Med.Schedule.Manager.Api\Fiap.Health.Med.Schedule.Manager.Api.csproj'